[[plugins]]
repo = 'Shougo/neocomplete.vim'
depends = 'context_filetype.vim'
if = "has('lua')"
on_event= 'InsertEnter'
hook_source= '''
  let g:neocomplete#enable_at_startup=1
  source ~/.vim/rc/plugins/neocomplete.rc.vim
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets','context_filetype.vim']
on_event='InsertCharPre'
on_ft='snippet'
hook_source='''
  imap<silent>L<Plug>(neosnippet_jump_or_expand)
  smap<silent>L<Plug>(neosnippet_jump_or_expand)
  xmap<silent>L<Plug>(neosnippet_expand_target)

  let g:neosnippet#enable_snipmate_compatibility = 1
  let g:neosnippet#enable_complete_done = 1
  let g:neosnippet#expand_word_boundary = 1
'''

[[plugins]]
repo = 'Shougo/vimshell.vim'
on_map = { n = '<Plug>'}
hook_add = 'nmap [Space]s <Plug>(cimshell_switch)'
# 必要?
# hook_source = 'source ~/.vim/rc/plugins/vimshell.rc.vim'

[[plugins]]
repo = 'kannokanno/previm'
on_cmd = 'PrevimOpen'
depends = 'open-browser.vim'


[[plugins]]
repo = 'aokiyuya/jedi-vim'
on_ft = 'python'


[[plugins]]
repo = 'ujihisa/neco-look'
on_source = [ 'neocomplete.vim' ]





