" my vim settings
" Author: Fujie lab members

set number
set noswapfile
set cmdheight=2
set title
set wildmenu
set smartcase
set hlsearch
set incsearch
set nocompatible
set whichwrap=b,s,h,l,<,>,[,]
set list
set listchars=tab:>-,extends:<,trail:-
set backspace=indent,eol,start
set tabstop=4
set ambiwidth=double
set runtimepath+=~/.vim/:~/.vim/ftplugin/
set encoding=utf-8
set fileencodings=iso-2022-jp,euc-jp,sjis,utf-8
" もしutf-8ですべてのファイルを管理したければ
set fileencoding=utf-8
set fileformats=unix,dos,mac

" Space をLeader にしてみる
let mapleader = "\<Space>"
" Space w で保存 Space q で終了
nnoremap <Leader>w :w<CR>
nnoremap <Leader>q :q<CR>
" Space SpaceでVisual Line
nnoremap <Leader><Leader> V
" 不要なウィンドウのポップアップを抑制
map q: :q

" OSの判定
if has('win32')
	let ostype = "Win"
elseif has('mac')
	let ostype = "Mac"
else
	let ostype = system("uname")
endif

" put esc-key for delete highlight
nmap <silent> <Esc><Esc> :nohlsearch<CR>

" reset augroup
augroup MyAutoCmd
  autocmd!
augroup END

" road template
autocmd BufNewFile *.py 0r $HOME/.vim/template/template.py
autocmd BufNewFile *.cpp 0r $HOME/.vim/template/template.cpp
autocmd BufNewFile *.c 0r $HOME/.vim/template/template.cpp
autocmd BufNewFile *.sh 0r $HOME/.vim/template/template.sh
autocmd BufNewFile *.tex 0r $HOME/.vim/template/template.tex


" shougo-s-githubを参考に改善してみた
" dein settings -----------------------------------------------------
" set cache path
let $CACHE = expand('~/.cache')
" Disable packpath
set packpath=

" Load dein
set runtimepath+=$CACHE/dein/repos/github.com/Shougo/dein.vim
let s:dein_dir = expand('$CACHE/dein')
if s:dein_dir != '' || &runtimepath !~ '/dein.vim'
  if s:dein_dir == '' && &runtimepath !~ '/dein.vim'
    let s:dein_dir = expand('$CACHE/dein')
    \. '/repos/github.com/Shougo/dein.vim'
    if !isdirectory(s:dein_dir)
      execute '!git clone https://github.com/Shougo/dein.vim' s:dein_dir
    endif
  endif
  execute 'set runtimepath+=' . substitute(
        \ fnamemodify(s:dein_dir, ':p') , '/$', '', '')
endif

let g:dein#install_progress_type = 'title'
let g:dein#install_message_type = 'none'
let g:dein#enable_notificiation = 1

let s:path = expand('$CACHE/dein')
if !dein#load_state(s:path)
  finish
endif

call dein#begin(s:path, expand('<sfile>'))
call dein#load_toml('~/.vim/rc/dein.toml', {'lazy': 0})
call dein#load_toml('~/.vim/rc/deinlazy.toml', {'lazy': 1})
call dein#end()
call dein#save_state()

if dein#check_install()
  call dein#install()
endif

if has('vim_starting') && dein#check_install()
  call dein#install()
endif

"End dein settings------------------------

" 引数なしでvimを開くとNERDTreeを起動
let file_name = expand('%')
if has('vim_starting') &&  file_name == ''
  autocmd VimEnter * NERDTree ./
endif

" ---------- neocomplete.vim設定 ----------
" Disable AutoComplPop.
let g:acp_enableAtStartup = 0
" Use neocomplete.
let g:neocomplete#enable_at_startup = 1
" Use smartcase.
let g:neocomplete#enable_smart_case = 1
" Set minimum syntax keyword length.
let g:neocomplete#sources#syntax#min_keyword_length = 3
let g:neocomplete#lock_buffer_name_pattern = '\*ku\*'
" Plugin key-mappings.
inoremap <expr><C-g>     neocomplete#undo_completion()
inoremap <expr><C-l>     neocomplete#complete_common_string()

" Recommended key-mappings.
" <CR>: close popup and save indent.
inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>
function! s:my_cr_function()
    " return neocomplete#close_popup() . '\<CR>'
" For no inserting <CR> key.
    return pumvisible() ? neocomplete#close_popup() : "\<CR>"
endfunction
" <TAB>: completion.
inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
" <C-h>, <BS>: close popup and delete backword char.
inoremap <expr><C-h> neocomplete#smart_close_popup()."\<C-h>"
inoremap <expr><BS> neocomplete#smart_close_popup()."\<C-h>"
inoremap <expr><C-y>  neocomplete#close_popup()
inoremap <expr><C-e>  neocomplete#cancel_popup()

" Close popup by <Space>.
inoremap <expr><Space> pumvisible() ? neocomplete#close_popup() :"\<Space>"

let g:precious_enable_switch_CursorMoved = { '*': 0, 'help': 1 }
autocmd MyAutoCmd InsertEnter * :PreciousSwitch
autocmd MyAutoCmd InsertLeave * :PreciousReset

""
"" quickrun
""
set visualbell
set vb t_vb=
autocmd FileType plaintex setlocal filetype=tex

if has("vim-quickrun")
  autocmd MyAutoCmd BufWritePost *.tex call quickrun#run() 
endif
let g:quickrun_config = {}
let g:quickrun_config.tex = {
            \ 'command' : 'latexmk',
            \ 'cmdopt' : '-pvc',
            \ 'outputter/error/error' : 'quickfix',
            \ "runner" : "vimproc",
            \ "runner/vimproc/updatetime" : 40,
            \ 'exec'      : '%c %o %s',
            \ }

" neosnippet
"
" SuperTab like snippets behavior.
imap <expr><TAB> neosnippet#expandable_or_jumpable() ?
\ "\<Plug>(neosnippet_expand_or_jump)"
\: pumvisible() ? "\<C-n>" : "\<TAB>"
smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
\ "\<Plug>(neosnippet_expand_or_jump)"
\: "\<TAB>"

" For snippet_complete marker.
if has('conceal')
  set conceallevel=2 concealcursor=i
endif

" status bar
set laststatus=2
set statusline=%F%m%r%h%w[%{&ff}]%=%{g:NyanModoki()}(%l,%c)[%P]
let g:nyan_modoki_select_cat_face_number = 2
let g:nyan_modoki_animation_enabled = 1



" colorscheme関係
colorscheme badwolf

" syntax on
" " 一応256色対応にしてみた
" set t_Co=256


" https://github.com/Shougo/dein.vim/issues/65
" needed らしいのでいれてみる
filetype plugin indent on
syntax enable
" 透過用処理らしい
highlight Normal ctermbg=none

