# 基本は github.com のレポジトリーを指定するだけ
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

# [[plugins]]
# repo = 'thinca/vim-quickrun'
# on_ft = 'tex'
# hook_source = '''source ~/.vim/rc/plugins/quickrun_tex.rc.vim'''
# depends = ['Shougo/vimproc.vim']

[[plugins]] # statusline の設定
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'tpope/vim-surround'

# ブランチやタグを指定したいとき
# [[plugins]]
# repo = 'delphinus35/typescript-vim'
# rev  = 'colorize-template-strings'

# 特定の条件で読み込みたいとき
# [[plugins]]
# repo = 'elzr/vim-json'
# if   = '''! has('kaoriya')'''
# on_ft = 'json'

# [[plugins]] # カーソル位置によって filetype 切り替え
# repo = 'osyo-manga/vim-precious'
# depends = ['Shougo/context_filetype.vim']

[[plugins]] # filetype 判定ライブラリ
repo = 'Shougo/context_filetype.vim'



[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

# [[plugins]]
# repo = 'scrooloose/nerdtree'

# [[plugins]]
# repo =  'evidens/vim-twig'

# [[plugins]]
# repo = 'scrooloose/syntastic'
# hook_add = '''
# let g:syntastic_check_on_wq = 0
# let g:loaded_syntastic_python_pylint_checker = 0
# '''

[[plugins]]
repo = 'aokiyuya/neosnippet-snippets'

# [[plugins]]
# repo = 'Shougo/vimshell'
# 
# [[plugins]]
# repo = 'supermomonga/vimshell-kawaii.vim'

# markdown用
[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = 'markdown'

# python用
# [[plugins]]
# repo = 'nathanaelkane/vim-indent-guides'
# on_ft = 'python'


# [[plugins]]
# repo = 'hdima/python-syntax'
# on_ft = 'python'

# [[plugins]]
# repo = 'hynek/vim-python-pep8-indent'
# on_ft = 'python'

[[plugins]]
repo = 'roxma/nvim-yarp'
if = "!has('nvim')"

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = "!has('nvim')"

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'
hook_source = '''
let g:python3_host_prog = systemlist('pyenv which python3 || which python3')[0]
let g:python_host_prog = systemlist('pyenv which python2 || which python2')[0]
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'Shougo/context_filetype.vim'
on_i = 1
hook_source ='''
let g:deoplete#enable_at_startup = 1
source ~/.vim/rc/plugins/deoplete.rc.vim
'''

# [[plugins]]
# repo = 'Shougo/neco-syntax'


# plugins for twitter
# [[plugins]]
# repo = 'basyura/TweetVim'
# on_ft = 'twitter'
# hook_source ='''
# source ~/.vim/rc/plugins/tweet.vim
# '''

# [[plugins]]
# repo = 'mattn/webapi-vim'
# on_ft = 'twitter'

# [[plugins]]
# repo = 'basyura/twibill.vim'
# on_ft = 'twitter'

# [[plugins]]
# repo = 'tyru/open-browser.vim'
# on_ft = 'twitter'

# [[plugins]]
# repo = 'h1mesuke/unite-outline'
# on_ft = 'twitter'

# [[plugins]]
# repo = 'basyura/bitly.vim'
# on_ft = 'twitter'

# [[plugins]]
# repo = 'Shougo/unite.vim'
# on_ft = 'twitter'


# new asynchronous sytax checker
[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
let g:ale_linters = {
\   'python': ['flake8'],
\   'vim': [],
\   'tex': [],
\   'java': [],
\}

'''


# [[plugins]]
# repo = 'tpope/vim-dispatch'


# [[plugins]] # カラースキーマ
# hook_add = '''
# set background=dark
# au MyAutoCmd VimEnter * nested colorscheme badwolf
# '''

# [[plugins]]
# repo = 'junegunn/vim-easy-align'
# hook_source = '''
# vmap <CR> <Plug>(EasyAlign)
# '''
# [[plugins]]
# repo = '5t111111/alt-gtags.vim'

[[plugins]]
repo = 'dag/vim-fish'
on_ft = 'fish'

[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
set background=dark
au MyAutoCmd VimEnter * nested colorscheme molokai
'''

# [[plugins]]
# repo = 'aokiyuya/shellnote.vim'
# on_ft = 'markdown'

# [[plugins]]
# repo = 'vim-scripts/autodate.vim'
# on_ft = 'vimrc'
