[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'Shougo/context_filetype.vim'
on_i = 1
hook_source ='''
let g:deoplete#enable_at_startup = 1
source ~/.vim/rc/plugins/deoplete.rc.vim
'''

[[plugins]]
repo = 'Shougo/context_filetype.vim'




