[[plugins]]
repo = 'Shougo/neocomplete.vim'
depends = 'context_filetype.vim'
if = "has('lua')"
on_event= 'InsertEnter'
hook_source= '''
source ~/.vim/rc/plugins/neocomplete.rc.vim
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets','context_filetype.vim']
on_event='InsertCharPre'
on_ft='snippet'
hook_source='''
  imap<silent>L<Plug>(neosnippet_jump_or_expand)
  smap<silent>L<Plug>(neosnippet_jump_or_expand)
  xmap<silent>L<Plug>(neosnippet_expand_target)

  let g:neosnippet#enable_snipmate_compatibility = 1
  let g:neosnippet#enable_complete_done = 1
  let g:neosnippet#expand_word_boundary = 1
'''

[[plugins]]
repo = 'Shougo/vimshell.vim'
on_map = { n = '<Plug>'}
hook_add = 'nmap [Space]s <Plug>(cimshell_switch)'
# hook_source = 'source ~/.vim/rc/plugins/vimshell.rc.vim'

[[plugins]]
repo = 'kannokanno/previm'
on_cmd = 'PrevimOpen'
depends = 'open-browser.vim'


[[plugins]]
repo = 'aokiyuya/jedi-vim'
on_event = 'InsertEnter'
on_ft = 'python'
hook_source = '''
source ~/.vim/rc/plugins/jedi.rc.vim

" setlocal omnifunc=jedi#completions
" let g:jedi#completions_enabled = 0
" let g:jedi#auto_vim_configuration = 1
" let g:jedi#popup_on_dot = 0
" let g:jedi#smart_auto_mappings = 0
" let g:jedi#show_call_signatures = 0
" setlocal completeopt-=preview
" 
" let g:jedi#completions_command = "<C-Space>"
" let g:jedi#goto_assignments_command = "<C-g>"
" let g:jedi#foto_definitions_command = "<C-d>"
" let g:jedi#documentation_commnad = "<C-k>"


'''

[[plugins]]
repo = 'ujihisa/neco-look'
on_source = [ 'neocomplete.vim' ]


