# 基本は github.com のレポジトリーを指定するだけ
[[plugins]]
repo = 'Shougo/dein.vim'

# git clone 後、実行すべきコマンドがある場合はこんな感じ
[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

# ブランチやタグを指定したいとき
[[plugins]]
repo = 'delphinus35/typescript-vim'
rev  = 'colorize-template-strings'

# 特定の条件で読み込みたいとき
[[plugins]]
repo = 'elzr/vim-json'
if   = '''! has('kaoriya')'''

# 依存関係を指定したいとき
[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

# 依存関係を指定したからと言って、自動でインストールはされない（ここは NeoBundle と違う）
[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]] # カラースキーマ
repo = 'sjl/badwolf'

[[plugins]] # カーソル位置によって filetype 切り替え
repo = 'osyo-manga/vim-precious'
depends = ['Shougo/context_filetype.vim']

[[plugins]] # filetype 判定ライブラリ
repo = 'Shougo/context_filetype.vim'

# lazyに移動するか?
[[plugin]]
repo = 'rhysd/github-complete.vim'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo =  'evidens/vim-twig'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'aokiyuya/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/vimshell'

[[plugins]]
repo = 'supermomonga/vimshell-kawaii.vim'

[[plugins]]
repo = 'drillbits/nyan-modoki.vim'

[[plugins]]
repo = 'Shougo/Unite.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

# markdown用
[[plugin]]
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'

[[plugin]]
repo = 'tyru/open-browser.vim'
on_ft = 'markdown'

# python用
[[plugin]]
repo = 'kevinw/pyflakes-vim'
on_ft = 'python'

[[plugin]]
repo = 'nathanaelkane/vim-indent-guides'
on_ft = 'python'

[[plugin]]
repo = 'hdima/python-syntax'
on_ft = 'python'

[[plugin]]
repo = 'jpythonfold.vim'
on_ft = 'python'

[[plugin]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'

# plugins for c and cpp
[[plugin]]
repo = 'osyo-manga/vim-marching'
on_ft = 'cpp'

[[plugin]]
repo = 'vim-jp/cpp-vim'
on_ft = 'cpp'

[[plugin]]
repo = 'justmao945/vim-clang'
on_ft = 'cpp'





