
[[plugins]]
repo = 'tweekmonster/deoplete-clang2'
on_ft = ['c', 'cpp']
hook_source = '''
  let b:clang2_orig_maps = {}
'''


[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'
hook_source = '''
let g:python3_host_prog = '/Users/aoki/.pyenv/shims/python3'
let g:python_host_prog = '/Users/aoki/.pyenv/shims/python'
let g:deoplete#sources#jedi#show_docstring = 1
call deoplete#custom#set('jedi', 'debug_enabled', 1)
call deoplete#enable_logging('DEBUG', '/tmp/deoplete.log')
'''

