[[plugins]]
repo = 'tweekmonster/deoplete-clang2'
on_ft = ['c', 'cpp']
hook_source = '''
  let b:clang2_orig_maps = {}
'''
depends = ['deoplete.nvim']


[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'
hook_source = '''
let g:python3_host_prog = systemlist('pyenv which python3 || which python3')[0]
let g:python_host_prog = systemlist('pyenv which python2 || which python2')[0]
let g:deoplete#sources#jedi#show_docstring = 1
call deoplete#custom#set('jedi', 'debug_enabled', 1)
call deoplete#enable_logging('DEBUG', '/tmp/deoplete.log')
'''
depends = ['deoplete.nvim']
